### ISSUE TITLE
Using $_FILES to download?

### ISSUE THREAD

**Issue by ralphe-samson** [saleemkce/downloadable#2]
How come you are using $_FILES in your script? As far as I know $_FILES is using for uploading files. Wouldnt it be more proper to use another temporary file name?

**Comment by saleemkce** [comment]
@ralphe-samson  yes, using **$_FILES["file"]["tmp_name"]** for downloading a file is one of acceptable ways.  This is working code for large download in PHP. Let me know if otherwise.
